### ISSUE TITLE
Compiling error ev3dev.h is missing - remove dependency of ev3dev cpp library

### ISSUE THREAD

**Issue by RodBelaFarin** [Hacks4ROS/h4r_ev3_ctrl#1]
Hi, I am just trying your EV3 package. I set may EV3 up like mentioned in your instructions, YOCTO runs fine.

But compiling the package on my computer fails due to an error. ev3dev.h is missing.

```
In file included from /home/ros/ev3_ws/src/h4r_ev3_ctrl/h4r_ev3_manager/src/h4r_ev3_manager/Ev3HardwareInterface.cpp:23:0:
/home/ros/ev3_ws/src/h4r_ev3_ctrl/h4r_ev3_manager/src/h4r_ev3_manager/../h4r_ev3_manager/Ev3HardwareInterface.h:28:20: fatal error: ev3dev.h: No such file or directory
 #include <ev3dev.h>
                    ^
compilation terminated.
In file included from /home/ros/ev3_ws/src/h4r_ev3_ctrl/h4r_ev3_manager/src/h4r_ev3_manager/ev3_ctrl_node.cpp:29:0:
/home/ros/ev3_ws/src/h4r_ev3_ctrl/h4r_ev3_manager/src/h4r_ev3_manager/Ev3HardwareInterface.h:28:20: fatal error: ev3dev.h: No such file or directory
 #include <ev3dev.h>
```

```
                ^
```

compilation terminated.

**Comment by cyborg-x1** [comment]
Ahh, yes you currently still need the ev3dev library for cpp development to compile, I need to get rid of that dependency .. actually not much should be used from it any more ... 
I try to remove that, maybe on the weekend - meanwhile you can get the library from the ev3dev project and compile it on your own for your pc. It should compile without needing anything additional, just reads and writes to special sys-directories of the EV3dev drivers.

**Comment by RodBelaFarin** [comment]
Can you maybe send me a URL? I can't really find it. :D

**Comment by cyborg-x1** [comment]
Here you go: https://github.com/ev3dev/ev3dev-lang/tree/master/cpp
