### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by yrosascu** [Hacks4ROS/h4r_ev3_ctrl#9]
I am new in ROS and I try to connect my ev3 with my computer by wired but i didn't succed. 
I want to buy a wi-fi dongle so i don't know what kind of dongle to buy. Anyone have any suggest? that work with ev3 and pc on Yocto with ROS.
Thank!

**Comment by cyborg-x1** [comment]
Hi, as already mentioned in the howto:


> Warning
>     There is an driver issue for some wireless adapters, I can recommend you the EDIMAX EW-7811Un (known from RaspberryPI) at the moment, if your own does not work.

https://www.amazon.com/Edimax-EW-7811Un-150Mbps-Raspberry-Supports/dp/B003MTTJOY/ref=sr_1_1?ie=UTF8&qid=1486768609&sr=8-1&keywords=EDIMAX+EW-7811Un

This one works for me.

**Comment by yrosascu** [comment]
Hello,
I bought the network adapter, but I can not connect the ev3 and the pc.
I have connected in ev3dev and the pc by wifi and it works, here in yocto I used a hub to be able to connect the keyboard and the adapter at the same time and with the help of the command `connmanctl` I tried to configure the network but I have not succeeded.
Is there a form of connection? How can I achieve this connection if I need to use the usb port of ev3 for both the keyboard and the wifi adapter.

**Comment by cyborg-x1** [comment]
What about using an [USB Hub](https://www.google.com/search?tbm=isch&q=USB+Hub)? :wink:

**Comment by cyborg-x1** [comment]
You already did, using a USB Hub. There is nothing more ...

**Comment by cyborg-x1** [comment]
Can you explain a bit further the detail, about what is not working?
Keyboard does not work?
Wifi Dongle does not work?
No networks found?
Configuration does not work?
By this small amount of details I just can not help you.

(It could also be, that you need a powered hub... depending on your Keyboard/Dongle)
